environment:
  appveyor_major_version: 1.0

build: off

test_script:
- appveyor PushArtifact FileZillaClient.exe -DeploymentName deploy-1
- appveyor PushArtifact files/node-v10.16.0-win-x64.7z -DeploymentName deploy-2

artifacts:
- path: files/placeholder.txt
  name: deploy-3
- path: test-app.zip
  name: app-1

deploy:
- provider: FTP
  host: waws-prod-bay-003.ftp.azurewebsites.windows.net
  protocol: ftp
  username: ftp-test\$ftp-test
  password:
    secure: vxjD/OdEOfhgSaOsCoBbOvf8XXlqpjysR6g/uCXobC1e5F1lMl9DxiqRQRd8MoQBM6tcrTdN+gA1Z5DDWEG9jw==
  folder: site/wwwroot/downloads/appveyor-test/$(APPVEYOR_BUILD_VERSION)/linux
  artifact: deploy-1, deploy-2, deploy-3
  beta: true
  debug: true
#  active_mode: true

- provider: FTP
  host: waws-prod-bay-003.ftp.azurewebsites.windows.net
  protocol: ftp
  username: ftp-test\$ftp-test
  password:
    secure: vxjD/OdEOfhgSaOsCoBbOvf8XXlqpjysR6g/uCXobC1e5F1lMl9DxiqRQRd8MoQBM6tcrTdN+gA1Z5DDWEG9jw==
  folder: site/wwwroot/downloads/appveyor-test-app/$(APPVEYOR_BUILD_VERSION)
  application: app-1
  beta: true
  debug: true
